# Generated by Django 5.0.7 on 2024-07-27 00:30

import django.utils.timezone
import django_resized.forms
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(db_index=True, max_length=15, unique=True)),
                ('email', models.CharField(db_index=True, max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=30)),
                ('bio', models.TextField(blank=True, max_length=100)),
                ('profile_pic', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='profile_pictures/default_profile_pic.jpg', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='profile_pictures/')),
                ('signup_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('blocked_accounts', models.ManyToManyField(blank=True, related_name='all_blocked_accounts', to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(blank=True, related_name='all_followers', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(blank=True, related_name='all_following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
