# Generated by Django 5.0.7 on 2024-07-30 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='blocked_accounts',
        ),
        migrations.RemoveField(
            model_name='account',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='account',
            name='following',
        ),
    ]
