# Generated by Django 5.0.7 on 2024-08-15 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('tweets', '0004_alter_tweet_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='tweet',
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient_tweet',
            field=models.ForeignKey(blank=True, help_text='The tweet that has been quoted/retweet/replied to etc.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tweets.tweet'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_tweet',
            field=models.ForeignKey(blank=True, help_text='The tweet that triggered the notification.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trigger_notifications', to='tweets.tweet'),
        ),
    ]
