# Generated by Django 5.0.7 on 2024-07-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_type',
            field=models.CharField(choices=[('TWEET', 'TWEET'), ('RETWEET', 'RETWEET'), ('REPLY', 'REPLY'), ('QUOTE', 'QUOTE')], default='TWEET', max_length=10),
        ),
        migrations.DeleteModel(
            name='Retweet',
        ),
    ]
