# Generated by Django 5.0.7 on 2024-08-02 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_alter_tweet_tweet_type_delete_retweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='referenced_tweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_tweets', to='tweets.tweet'),
        ),
    ]
