# pull the official base image
FROM python:3.11-slim-bookworm


# set work directory
WORKDIR /usr/project/backend/


# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


# install dependencies
RUN pip install --upgrade pip 
COPY ./requirements.txt .
RUN pip install -r requirements.txt
RUN [ "python", "-c", "import nltk; nltk.download('stopwords', download_dir='/usr/local/nltk_data')" ] 


# copy project into docker container's work directory
COPY . .